/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.capycar.view;

import com.capycar.connection.GastoRiderAPI;
import com.capycar.controller.ProprietarioController;
import com.capycar.model.Proprietario;
import java.awt.Color;
import java.io.IOException;
import javax.swing.border.EmptyBorder;
import java.lang.String;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class ProprietarioView extends javax.swing.JFrame {

    /**
     * Creates new form ProprietarioView
     */
    private ProprietarioController proprietarioControle = new ProprietarioController();
    String tipoPessoa = "";
    String tabela = "Proprietario";

    public ProprietarioView() {
        initComponents();
        setLocationRelativeTo(null);

        if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
            setLocationRelativeTo(null);
            jTextNomeRazao.setVisible(false);
            jTextEmail.setVisible(false);
            jTextCPFCNPJ.setVisible(false);
            jLabelNomeRazao.setVisible(false);
            jLabelEmail.setVisible(false);
            jLabelCPFCNPJ.setVisible(false);
            jComboBoxCNH.setVisible(false);
            jLabelCNH.setVisible(false);
        } else {
            jRadioCPF.setEnabled(false);
            jRadioCNPJ.setEnabled(false);
            jTextCPFCNPJ.setEditable(false);
            jTextBairro.setEditable(false);
            jTextCEP.setEditable(false);
            jTextCidade.setEditable(false);
            jTextComplemento.setEditable(false);
            jTextDDD.setEditable(false);
            jTextDDI.setEditable(false);
            jTextEmail.setEditable(false);
            jTextLogradouro.setEditable(false);
            jTextNomeRazao.setEditable(false);
            jTextNumero.setEditable(false);
            jTextNumeroCasa.setEditable(false);
            jComboBoxCNH.setEditable(false);
            jComboBoxEstado.setEditable(false);
            jDateDataNasCri.setEnabled(false);;
            jTextCPFCNPJ.setForeground(Color.GRAY);
            jTextBairro.setForeground(Color.GRAY);
            jTextCEP.setForeground(Color.GRAY);
            jTextCidade.setForeground(Color.GRAY);
            jTextComplemento.setForeground(Color.GRAY);
            jTextDDD.setForeground(Color.GRAY);
            jTextDDI.setForeground(Color.GRAY);
            jTextEmail.setForeground(Color.GRAY);
            jTextLogradouro.setForeground(Color.GRAY);
            jTextNomeRazao.setForeground(Color.GRAY);
            jTextNumero.setForeground(Color.GRAY);
            jTextNumeroCasa.setForeground(Color.GRAY);
            jComboBoxCNH.setForeground(Color.GRAY);
            jComboBoxEstado.setForeground(Color.GRAY);
            preencherCampos(proprietarioControle.consultarProprietario(tabela));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioCPF = new javax.swing.JRadioButton();
        jRadioCNPJ = new javax.swing.JRadioButton();
        jLabelNomeRazao = new javax.swing.JLabel();
        jTextNomeRazao = new javax.swing.JTextField();
        jLabelCPFCNPJ = new javax.swing.JLabel();
        jTextCPFCNPJ = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextDDI = new javax.swing.JTextField();
        jTextDDD = new javax.swing.JTextField();
        jTextNumero = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextCEP = new javax.swing.JTextField();
        jTextNumeroCasa = new javax.swing.JTextField();
        jTextBairro = new javax.swing.JTextField();
        jTextLogradouro = new javax.swing.JTextField();
        jTextComplemento = new javax.swing.JTextField();
        jTextCidade = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabelCNH = new javax.swing.JLabel();
        jComboBoxCNH = new javax.swing.JComboBox();
        jDateDataNasCri = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        jPanel2.setBackground(new java.awt.Color(121, 113, 234));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Capycar menu.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(121, 113, 234));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(34, 40, 49));
        jButton1.setText("Cadastro de Proprietário");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(121, 113, 234));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(34, 40, 49));
        jButton2.setText("Lançamento de gastos");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(121, 113, 234));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(34, 40, 49));
        jButton3.setText("Cadastro de Marca");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(121, 113, 234));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(34, 40, 49));
        jButton4.setText("Cadastro de Modelo");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(121, 113, 234));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(34, 40, 49));
        jButton5.setText("Cadastro de Categorias");
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(121, 113, 234));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(34, 40, 49));
        jButton6.setText("Cadastro de Veiculo");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(121, 113, 234));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton7.setForeground(new java.awt.Color(34, 40, 49));
        jButton7.setText("Relatórios");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(jButton2)
                        .addComponent(jButton7)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Cadastro de Proprietário");

        jRadioCPF.setBackground(new java.awt.Color(57, 62, 70));
        buttonGroup1.add(jRadioCPF);
        jRadioCPF.setForeground(new java.awt.Color(238, 238, 238));
        jRadioCPF.setText("CPF");
        jRadioCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCPFActionPerformed(evt);
            }
        });

        jRadioCNPJ.setBackground(new java.awt.Color(57, 62, 70));
        buttonGroup1.add(jRadioCNPJ);
        jRadioCNPJ.setForeground(new java.awt.Color(238, 238, 238));
        jRadioCNPJ.setText("CNPJ");
        jRadioCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCNPJActionPerformed(evt);
            }
        });

        jLabelNomeRazao.setForeground(new java.awt.Color(238, 238, 238));
        jLabelNomeRazao.setText("Nome:");

        jTextNomeRazao.setBorder(new EmptyBorder(5, 10, 5, 10));
        jTextNomeRazao.setBackground(new java.awt.Color(217, 217, 217));
        jTextNomeRazao.setForeground(new java.awt.Color(0, 0, 0));

        jLabelCPFCNPJ.setForeground(new java.awt.Color(238, 238, 238));
        jLabelCPFCNPJ.setText("CPF");

        jTextCPFCNPJ.setBackground(new java.awt.Color(217, 217, 217));
        jTextCPFCNPJ.setForeground(new java.awt.Color(0, 0, 0));
        jTextCPFCNPJ.setBorder(null);

        jLabelEmail.setForeground(new java.awt.Color(238, 238, 238));
        jLabelEmail.setText("Email");

        jTextEmail.setBackground(new java.awt.Color(217, 217, 217));
        jTextEmail.setForeground(new java.awt.Color(0, 0, 0));
        jTextEmail.setBorder(null);

        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Telefone:");

        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("DDI:");

        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("DDD:");

        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("Número:");

        jTextDDI.setBackground(new java.awt.Color(217, 217, 217));
        jTextDDI.setForeground(new java.awt.Color(0, 0, 0));
        jTextDDI.setBorder(null);
        jTextDDI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextDDIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextDDIKeyReleased(evt);
            }
        });

        jTextDDD.setBackground(new java.awt.Color(217, 217, 217));
        jTextDDD.setForeground(new java.awt.Color(0, 0, 0));
        jTextDDD.setBorder(null);
        jTextDDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextDDDKeyReleased(evt);
            }
        });

        jTextNumero.setBackground(new java.awt.Color(217, 217, 217));
        jTextNumero.setForeground(new java.awt.Color(0, 0, 0));
        jTextNumero.setBorder(null);
        jTextNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNumeroKeyReleased(evt);
            }
        });

        jLabelData.setForeground(new java.awt.Color(238, 238, 238));
        jLabelData.setText("Data de Nascimento:");

        jLabel8.setForeground(new java.awt.Color(238, 238, 238));
        jLabel8.setText("Endereço:");

        jLabel9.setForeground(new java.awt.Color(238, 238, 238));
        jLabel9.setText("CEP:");

        jLabel10.setForeground(new java.awt.Color(238, 238, 238));
        jLabel10.setText("Logradouro:");

        jLabel11.setForeground(new java.awt.Color(238, 238, 238));
        jLabel11.setText("Número:");

        jLabel12.setForeground(new java.awt.Color(238, 238, 238));
        jLabel12.setText("Bairro:");

        jLabel14.setForeground(new java.awt.Color(238, 238, 238));
        jLabel14.setText("Complemento:");

        jLabel16.setForeground(new java.awt.Color(238, 238, 238));
        jLabel16.setText("Cidade:");

        jLabel17.setForeground(new java.awt.Color(238, 238, 238));
        jLabel17.setText("Estado:");

        jTextCEP.setBackground(new java.awt.Color(217, 217, 217));
        jTextCEP.setForeground(new java.awt.Color(0, 0, 0));
        jTextCEP.setBorder(null);
        jTextCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCEPKeyReleased(evt);
            }
        });

        jTextNumeroCasa.setBackground(new java.awt.Color(217, 217, 217));
        jTextNumeroCasa.setForeground(new java.awt.Color(0, 0, 0));
        jTextNumeroCasa.setBorder(null);

        jTextBairro.setBackground(new java.awt.Color(217, 217, 217));
        jTextBairro.setForeground(new java.awt.Color(0, 0, 0));
        jTextBairro.setBorder(null);

        jTextLogradouro.setBackground(new java.awt.Color(217, 217, 217));
        jTextLogradouro.setForeground(new java.awt.Color(0, 0, 0));
        jTextLogradouro.setBorder(null);

        jTextComplemento.setBackground(new java.awt.Color(217, 217, 217));
        jTextComplemento.setForeground(new java.awt.Color(0, 0, 0));
        jTextComplemento.setBorder(null);

        jTextCidade.setBackground(new java.awt.Color(217, 217, 217));
        jTextCidade.setForeground(new java.awt.Color(0, 0, 0));
        jTextCidade.setBorder(null);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jButtonSalvar.setBackground(new java.awt.Color(121, 113, 234));
        jButtonSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(34, 40, 49));
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(121, 113, 234));
        jButtonAlterar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(34, 40, 49));
        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabelCNH.setForeground(new java.awt.Color(238, 238, 238));
        jLabelCNH.setText("Categoria CNH:");

        jComboBoxCNH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "C", "D", "E", "AC", "AD", "AE" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNomeRazao)
                                    .addComponent(jTextNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCPFCNPJ)
                                    .addComponent(jTextCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4)
                                                .addComponent(jTextDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGap(36, 36, 36)
                                                            .addComponent(jLabel10))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGap(38, 38, 38)
                                                            .addComponent(jLabel6)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jTextDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabelCNH)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jComboBoxCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(0, 0, Short.MAX_VALUE))))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(37, 37, 37)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelData)
                                        .addComponent(jDateDataNasCri, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(13, 13, 13))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(281, 281, 281))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(92, 92, 92)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jTextComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jRadioCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioCNPJ))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel2)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioCPF)
                    .addComponent(jRadioCNPJ))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNomeRazao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCPFCNPJ)
                            .addComponent(jLabelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCPFCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jTextEmail))))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabelData)
                    .addComponent(jLabelCNH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateDataNasCri, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCNH, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addGap(1, 1, 1)))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ProprietarioView proprietario = new ProprietarioView();
        proprietario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCPFActionPerformed
        jTextNomeRazao.setVisible(true);
        jTextEmail.setVisible(true);
        jTextCPFCNPJ.setVisible(true);
        jLabelNomeRazao.setVisible(true);
        jLabelEmail.setVisible(true);
        jLabelCPFCNPJ.setVisible(true);
        jLabelNomeRazao.setText("Nome:");
        jLabelCPFCNPJ.setText("CPF:");
        jLabelData.setText("Data de Nascimento:");
        jComboBoxCNH.setVisible(true);
        jLabelCNH.setVisible(true);
        tipoPessoa = "PF";
    }//GEN-LAST:event_jRadioCPFActionPerformed

    private void jRadioCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCNPJActionPerformed
        jTextNomeRazao.setVisible(true);
        jTextEmail.setVisible(true);
        jTextCPFCNPJ.setVisible(true);
        jLabelNomeRazao.setVisible(true);
        jLabelEmail.setVisible(true);
        jLabelCPFCNPJ.setVisible(true);
        jLabelNomeRazao.setText("Razão Social:");
        jLabelCPFCNPJ.setText("CNPJ:");
        jLabelData.setText("Data de criação:");
        jComboBoxCNH.setVisible(false);
        jLabelCNH.setVisible(false);
        tipoPessoa = "PJ";
    }//GEN-LAST:event_jRadioCNPJActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setVisible(false);
        HomeView home = new HomeView();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jTextBairro.getText().isEmpty() == true || jTextCPFCNPJ.getText().isEmpty() == true || jTextCEP.getText().isEmpty() == true || jTextCidade.getText().isEmpty() == true || jTextDDD.getText().isEmpty() == true || jTextDDI.getText().isEmpty() == true
                || jTextEmail.getText().isEmpty() == true || jTextLogradouro.getText().isEmpty() == true || jTextNomeRazao.getText().isEmpty() == true || jTextNumero.getText().isEmpty() == true || jTextNumeroCasa.getText().isEmpty() == true || jDateDataNasCri.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            return;
        }
        if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
            String telefone = jTextDDI.getText() + ";" + jTextDDD.getText() + ";" + jTextNumero.getText();
            Proprietario proprietario = new Proprietario(jTextCPFCNPJ.getText(), jTextNomeRazao.getText(), jTextEmail.getText(), telefone, jComboBoxCNH.getSelectedItem().toString(), jDateDataNasCri.getDate(), jTextCEP.getText(), jTextLogradouro.getText(),
                    jTextNumeroCasa.getText(), jTextBairro.getText(), jTextCidade.getText(), jComboBoxEstado.getSelectedItem().toString(), jTextComplemento.getText(), tipoPessoa);
            proprietarioControle.incluirProprietario(proprietario);
        } else {
            String telefone = jTextDDI.getText() + ";" + jTextDDD.getText() + ";" + jTextNumero.getText();
            Proprietario proprietario = new Proprietario(jTextCPFCNPJ.getText(), jTextNomeRazao.getText(), jTextEmail.getText(), telefone, jComboBoxCNH.getSelectedItem().toString(), jDateDataNasCri.getDate(), jTextCEP.getText(), jTextLogradouro.getText(),
                    jTextNumeroCasa.getText(), jTextBairro.getText(), jTextCidade.getText(), jComboBoxEstado.getSelectedItem().toString(), jTextComplemento.getText(), tipoPessoa);
            proprietarioControle.alterarProprietario(proprietario);
        }
        if (GastoRiderAPI.tabelaPossuiDados(tabela) == true) {
            jRadioCPF.setEnabled(false);
            jRadioCNPJ.setEnabled(false);
            jTextCPFCNPJ.setEditable(false);
            jTextBairro.setEditable(false);
            jTextCEP.setEditable(false);
            jTextCidade.setEditable(false);
            jTextComplemento.setEditable(false);
            jTextDDD.setEditable(false);
            jTextEmail.setEditable(false);
            jTextLogradouro.setEditable(false);
            jTextNomeRazao.setEditable(false);
            jTextNumero.setEditable(false);
            jTextNumeroCasa.setEditable(false);
            jComboBoxCNH.setEditable(false);
            jComboBoxEstado.setEditable(false);
            jTextCPFCNPJ.setForeground(Color.GRAY);
            jTextBairro.setForeground(Color.GRAY);
            jTextCEP.setForeground(Color.GRAY);
            jTextCidade.setForeground(Color.GRAY);
            jTextComplemento.setForeground(Color.GRAY);
            jTextDDD.setForeground(Color.GRAY);
            jTextDDI.setForeground(Color.GRAY);
            jTextEmail.setForeground(Color.GRAY);
            jTextLogradouro.setForeground(Color.GRAY);
            jTextNomeRazao.setForeground(Color.GRAY);
            jTextNumero.setForeground(Color.GRAY);
            jTextNumeroCasa.setForeground(Color.GRAY);
            jComboBoxCNH.setForeground(Color.GRAY);
            jComboBoxEstado.setForeground(Color.GRAY);
            preencherCampos(proprietarioControle.consultarProprietario(tabela));

        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jTextBairro.setEditable(true);
        jTextCEP.setEditable(true);
        jTextCidade.setEditable(true);
        jTextComplemento.setEditable(true);
        jTextDDD.setEditable(true);
        jTextDDI.setEditable(true);
        jDateDataNasCri.setEnabled(true);
        jTextEmail.setEditable(true);
        jTextLogradouro.setEditable(true);
        jTextNomeRazao.setEditable(true);
        jTextNumero.setEditable(true);
        jTextNumeroCasa.setEditable(true);
        jComboBoxCNH.setEditable(true);
        jComboBoxEstado.setEditable(true);
        jTextCPFCNPJ.setForeground(Color.GRAY);
        jTextBairro.setForeground(Color.BLACK);
        jTextCEP.setForeground(Color.BLACK);
        jTextCidade.setForeground(Color.BLACK);
        jTextComplemento.setForeground(Color.BLACK);
        jTextDDD.setForeground(Color.BLACK);
        jTextDDI.setForeground(Color.BLACK);
        jTextEmail.setForeground(Color.BLACK);
        jTextLogradouro.setForeground(Color.BLACK);
        jTextNomeRazao.setForeground(Color.BLACK);
        jTextNumero.setForeground(Color.BLACK);
        jTextNumeroCasa.setForeground(Color.BLACK);
        jComboBoxCNH.setForeground(Color.BLACK);
        jComboBoxEstado.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        VeiculoView veiculo = null;
        try {
            if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
                JOptionPane.showMessageDialog(null, "Cadastre seus dados em Cadastro de proprietário antes de usar esta tela");
            } else {
                setVisible(false);
                veiculo = new VeiculoView();
                veiculo.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextDDIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDDIKeyPressed

    }//GEN-LAST:event_jTextDDIKeyPressed

    private void jTextDDIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDDIKeyReleased
        jTextDDI.setText(jTextDDI.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jTextDDIKeyReleased

    private void jTextDDDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDDDKeyReleased
        jTextDDD.setText(jTextDDD.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jTextDDDKeyReleased

    private void jTextNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumeroKeyReleased
        jTextNumero.setText(jTextNumero.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jTextNumeroKeyReleased

    private void jTextCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCEPKeyReleased
        jTextCEP.setText(jTextCEP.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jTextCEPKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MarcaView marca = null;
        try {
            if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
                JOptionPane.showMessageDialog(null, "Cadastre seus dados em Cadastro de proprietário antes de usar esta tela");
            } else {
                setVisible(false);
                marca = new MarcaView();
                marca.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ModeloView modelo = null;
        try {
            if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
                JOptionPane.showMessageDialog(null, "Cadastre seus dados em Cadastro de proprietário antes de usar esta tela");
            } else {
                setVisible(false);
                modelo = new ModeloView();
                modelo.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
                JOptionPane.showMessageDialog(null, "Cadastre seus dados em Cadastro de proprietário antes de usar esta tela");
            } else {
                setVisible(false);
                CategoriaView categoria = new CategoriaView();
                categoria.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LancamentoView lancamentoView = null;
        try {
            if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
                JOptionPane.showMessageDialog(null, "Cadastre seus dados em Cadastro de proprietário antes de usar esta tela");
            } else {
                setVisible(false);
                lancamentoView = new LancamentoView();
                lancamentoView.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (GastoRiderAPI.tabelaPossuiDados(tabela) == false) {
            JOptionPane.showMessageDialog(null, "Cadastre seus dados em Cadastro de proprietário antes de usar esta tela");
        } else {
            setVisible(false);
            RelatorioView relatorioView = null;
            relatorioView = new RelatorioView();
            relatorioView.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void preencherCampos(Proprietario proprietario) {
        if (proprietario.getTipoPessoa() == "PF") {
            jRadioCPF.setSelected(true);
        }
        if (proprietario.getTipoPessoa() == "PJ") {
            jRadioCNPJ.setSelected(true);
        }

        String[] substrings = separarString(proprietario.getTelefone());

        jTextNomeRazao.setText(proprietario.getNome());
        jTextCPFCNPJ.setText(proprietario.getCPF_CNPJ());
        jTextEmail.setText(proprietario.getEmail());
        jTextDDI.setText(substrings[0]);
        jTextDDD.setText(substrings[1]);
        jTextNumero.setText(substrings[2]);
        jComboBoxCNH.setSelectedItem(proprietario.getCategoriaCNH());
        jDateDataNasCri.setDate(proprietario.getDataNasCria());
        jTextCEP.setText(proprietario.getCEP());
        jTextLogradouro.setText(proprietario.getLogradouro());
        jTextNumeroCasa.setText(proprietario.getNumero());
        jTextComplemento.setText(proprietario.getComplemento());
        jTextBairro.setText(proprietario.getBairro());
        jTextCidade.setText(proprietario.getCidade());
        jComboBoxEstado.setSelectedItem(proprietario.getEstado());
    }

    public static String[] separarString(String texto) {
        return texto.split(";");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProprietarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCNH;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private com.toedter.calendar.JDateChooser jDateDataNasCri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCNH;
    private javax.swing.JLabel jLabelCPFCNPJ;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNomeRazao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioCNPJ;
    private javax.swing.JRadioButton jRadioCPF;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCEP;
    private javax.swing.JTextField jTextCPFCNPJ;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextComplemento;
    private javax.swing.JTextField jTextDDD;
    private javax.swing.JTextField jTextDDI;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextLogradouro;
    private javax.swing.JTextField jTextNomeRazao;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextNumeroCasa;
    // End of variables declaration//GEN-END:variables
}
