/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.capycar.view;

import com.capycar.controller.LancamentoController;
import com.capycar.model.Categoria;
import com.capycar.model.Lancamento;
import com.capycar.model.Modelo;
import com.capycar.model.Proprietario;
import com.capycar.model.Subcategoria;
import com.capycar.model.Veiculo;
import com.capycar.controller.ReportController;
import com.capycar.ordenation.Ordenation;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.border.EmptyBorder;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class RelatorioView extends javax.swing.JFrame {

    LancamentoController lancamentoController = new LancamentoController();
    ArrayList<Veiculo> listaVeiculo = new ArrayList<>();
    ArrayList<Categoria> listaCategoria = new ArrayList<>();
    ArrayList<Subcategoria> listaSubCategoria = new ArrayList<>();
    Date date = new Date();
    Lancamento lancamento = null;
    ArrayList<Lancamento> listLancamento = null;

    public RelatorioView() {
        try {
            initComponents();
            jDateFim.setDate(date);
            setLocationRelativeTo(null);
            carregaComboBox();
            carregaProprietario();
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCPF_CNPJ = new javax.swing.JTextField();
        jTextFieldProprietario = new javax.swing.JTextField();
        jComboBoxVeiculo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSubCategoria = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jDateInicio = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateFim = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLancamento = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonExportarPDF = new javax.swing.JButton();
        jButtonGerarGrafico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonCategoria = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(57, 62, 70));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Relatórios");

        jTextFieldCPF_CNPJ.setBorder(new EmptyBorder(5, 10, 5, 10));
        jTextFieldCPF_CNPJ.setBackground(new java.awt.Color(217, 217, 217));
        jTextFieldCPF_CNPJ.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCPF_CNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF_CNPJActionPerformed(evt);
            }
        });

        jTextFieldCPF_CNPJ.setBorder(new EmptyBorder(5, 10, 5, 10));
        jTextFieldProprietario.setBackground(new java.awt.Color(217, 217, 217));
        jTextFieldProprietario.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldProprietario.setBorder(null);
        jTextFieldProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProprietarioActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Veiculo:");

        jComboBoxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCategoriaMouseClicked(evt);
            }
        });
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Categoria:");

        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("Subcategoria:");

        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("Data Inicio:");

        jTableLancamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableLancamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "VEICULO", "CATEGORIA", "SUBCATEGORIA", "VALOR", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLancamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableLancamento.setGridColor(new java.awt.Color(0, 0, 0));
        jTableLancamento.setRowHeight(50);
        jTableLancamento.setShowGrid(true);
        jTableLancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLancamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLancamento);

        jLabel7.setForeground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("Data Fim:");

        jLabel8.setForeground(new java.awt.Color(238, 238, 238));
        jLabel8.setText("CPF/CNPJ:");

        jLabel9.setForeground(new java.awt.Color(238, 238, 238));
        jLabel9.setText("Proprietário:");

        jButtonPesquisar.setBackground(new java.awt.Color(121, 113, 234));
        jButtonPesquisar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(34, 40, 49));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonExportarPDF.setBackground(new java.awt.Color(121, 113, 234));
        jButtonExportarPDF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonExportarPDF.setForeground(new java.awt.Color(34, 40, 49));
        jButtonExportarPDF.setText("Exportar PDF");
        jButtonExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarPDFActionPerformed(evt);
            }
        });

        jButtonGerarGrafico.setBackground(new java.awt.Color(121, 113, 234));
        jButtonGerarGrafico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonGerarGrafico.setForeground(new java.awt.Color(34, 40, 49));
        jButtonGerarGrafico.setText("Gerar Gráfico");
        jButtonGerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarGraficoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(121, 113, 234));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Capycar menu.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(121, 113, 234));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(34, 40, 49));
        jButton1.setText("Cadastro de Proprietário");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(121, 113, 234));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(34, 40, 49));
        jButton2.setText("Lançamento de gastos");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(121, 113, 234));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(34, 40, 49));
        jButton3.setText("Cadastro de Marca");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(121, 113, 234));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(34, 40, 49));
        jButton4.setText("Cadastro de Modelo");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonCategoria.setBackground(new java.awt.Color(121, 113, 234));
        jButtonCategoria.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonCategoria.setForeground(new java.awt.Color(34, 40, 49));
        jButtonCategoria.setText("Cadastro de Categorias");
        jButtonCategoria.setBorder(null);
        jButtonCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(121, 113, 234));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(34, 40, 49));
        jButton6.setText("Cadastro de Veiculo");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(121, 113, 234));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton7.setForeground(new java.awt.Color(34, 40, 49));
        jButton7.setText("Relatórios");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonCategoria)
                        .addComponent(jButton6)
                        .addComponent(jButton2)
                        .addComponent(jButton7)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButtonCategoria)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel3))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFim, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExportarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGerarGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(70, 70, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonExportarPDF)
                    .addComponent(jButtonGerarGrafico))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addGap(77, 77, 77))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ProprietarioView proprietario = new ProprietarioView();
        proprietario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        LancamentoView lancamentoView = null;
        try {
            lancamentoView = new LancamentoView();
        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        lancamentoView.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            setVisible(false);
            MarcaView marca = new MarcaView();
            marca.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        ModeloView modelo = null;
        try {
            modelo = new ModeloView();
        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelo.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        try {
            setVisible(false);
            CategoriaView categoria = new CategoriaView();
            categoria.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            setVisible(false);
            VeiculoView veiculo = new VeiculoView();
            veiculo.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextFieldCPF_CNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF_CNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF_CNPJActionPerformed

    private void jTextFieldProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProprietarioActionPerformed

    private void jComboBoxCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaMouseClicked

    }//GEN-LAST:event_jComboBoxCategoriaMouseClicked

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        int selectedIndex = jComboBoxCategoria.getSelectedIndex() - 1;
        if (selectedIndex >= 1) {
            Categoria categoriaSelecionada = listaCategoria.get(selectedIndex - 1);
            ResultSet resultSet = lancamentoController.consultarLancamento("subcategoria where id_categoria = " + categoriaSelecionada.getidCategoria());
            try {
                while (resultSet.next()) {
                    Subcategoria subcategoria = new Subcategoria();
                    subcategoria.setIdSubcategoria(resultSet.getInt(1));
                    subcategoria.setDescricao(resultSet.getString(2));

                    listaSubCategoria.add(subcategoria);
                }
                jComboBoxSubCategoria.removeAllItems();
                jComboBoxSubCategoria.addItem("Todas");

                for (Subcategoria subcategoria : listaSubCategoria) {
                    jComboBoxSubCategoria.addItem(subcategoria);
                }
                listaSubCategoria.clear();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(LancamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        if (selectedIndex == 0) {
            jComboBoxSubCategoria.removeAllItems();
            jComboBoxSubCategoria.addItem("Todas");
            ResultSet resultSet = lancamentoController.consultarLancamento("subcategoria");
            try {
                while (resultSet.next()) {
                    Subcategoria subcategoria = new Subcategoria();
                    subcategoria.setIdSubcategoria(resultSet.getInt(1));
                    subcategoria.setDescricao(resultSet.getString(2));

                    listaSubCategoria.add(subcategoria);
                }
                jComboBoxSubCategoria.removeAllItems();
                jComboBoxSubCategoria.addItem("Todas");

                for (Subcategoria subcategoria : listaSubCategoria) {
                    jComboBoxSubCategoria.addItem(subcategoria);
                }
                listaSubCategoria.clear();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(LancamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        if (selectedIndex < 0) {
            jComboBoxSubCategoria.removeAllItems();
        }
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTableLancamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLancamentoMouseClicked
        Lancamento lancamento = new Lancamento();
        lancamento.setIdLancamento(Integer.parseInt(jTableLancamento.getValueAt(jTableLancamento.getSelectedRow(), 0).toString()));
        lancamento.setVeiculo((Veiculo) jTableLancamento.getValueAt(jTableLancamento.getSelectedRow(), 1));
        lancamento.setCategoria((Categoria) jTableLancamento.getValueAt(jTableLancamento.getSelectedRow(), 2));
        lancamento.setSubCategoria((Subcategoria) jTableLancamento.getValueAt(jTableLancamento.getSelectedRow(), 3));
        lancamento.setValor(Float.parseFloat(jTableLancamento.getValueAt(jTableLancamento.getSelectedRow(), 4).toString()));
        lancamento.setDataRegistro((Date) jTableLancamento.getValueAt(jTableLancamento.getSelectedRow(), 5));
    }//GEN-LAST:event_jTableLancamentoMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jComboBoxSubCategoria.getSelectedItem() == null || jDateInicio.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            return;
        }
        carregaTabela();
        lancamento = null;
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarPDFActionPerformed
        if (this.listLancamento == null || this.listLancamento.isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Não existe lançamentos para gerar relatório!");
        } else {
            Ordenation ordenation = new Ordenation();
            listLancamento = ordenation.quickSortByVeiculo(listLancamento, 0, listLancamento.size() - 1);
            ReportController report = new ReportController();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String dataInicio = format.format(jDateInicio.getDate());
            String dataFim = format.format(jDateFim.getDate());
            report.gerarRelatorioPdf(jTextFieldCPF_CNPJ.getText(), jTextFieldProprietario.getText(), jComboBoxVeiculo.getSelectedItem().toString(), jComboBoxCategoria.getSelectedItem().toString(), jComboBoxSubCategoria.getSelectedItem().toString(),
                    dataInicio, dataFim, listLancamento);
        }
    }//GEN-LAST:event_jButtonExportarPDFActionPerformed

    private void jButtonGerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarGraficoActionPerformed
        setVisible(false);
        RelatorioGraficoView relatorioGrafico = new RelatorioGraficoView();
        relatorioGrafico.setVisible(true);
    }//GEN-LAST:event_jButtonGerarGraficoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setVisible(false);
        RelatorioView relatorioView = null;
        relatorioView = new RelatorioView();
        relatorioView.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setVisible(false);
        HomeView home = new HomeView();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    public void carregaComboBox() throws SQLException {
        ResultSet resultSet = lancamentoController.consultarLancamento("Veiculo");
        Proprietario proprietario = new Proprietario();
        Modelo modelo = new Modelo();
        while (resultSet.next()) {
            Veiculo veiculo = new Veiculo();
            veiculo.setIdVeiculo(resultSet.getInt(1));
            veiculo.setPlaca(resultSet.getString(2));
            veiculo.setRenavam(resultSet.getString(3));
            veiculo.setAnoFabricacao(resultSet.getString(4));
            veiculo.setAnoModelo(resultSet.getString(5));
            veiculo.setCombustivel(resultSet.getString(6));
            veiculo.setKmAtual(resultSet.getInt(7));
            veiculo.setStatus(resultSet.getString(9));
            veiculo.setModelo(modelo = new Modelo(resultSet.getInt(10)));

            listaVeiculo.add(veiculo);
        }

        resultSet = lancamentoController.consultarLancamento("Categoria");
        while (resultSet.next()) {
            Categoria categoria = new Categoria();
            categoria.setidCategoria(resultSet.getInt(1));
            categoria.setDescricao(resultSet.getString(2));

            listaCategoria.add(categoria);
        }

        jComboBoxVeiculo.removeAllItems();
        jComboBoxVeiculo.addItem("Todos");
        jComboBoxCategoria.removeAllItems();
        jComboBoxCategoria.addItem("Selecione uma categoria:");
        jComboBoxCategoria.addItem("Todas");

        for (Veiculo veiculo : listaVeiculo) {
            jComboBoxVeiculo.addItem(veiculo);
        }
        for (Categoria categoria : listaCategoria) {
            jComboBoxCategoria.addItem(categoria);
        }
    }

    public void carregaTabela() {
        DefaultTableModel model = (DefaultTableModel) jTableLancamento.getModel();
        model.setNumRows(0);
        Veiculo veiculo;
        Categoria categoria;
        Subcategoria subcategoria;
        listLancamento = null;
        if (jComboBoxVeiculo.getSelectedItem() == "Todos") {
            veiculo = null;
        } else {
            veiculo = (Veiculo) jComboBoxVeiculo.getSelectedItem();
        }
        if (jComboBoxCategoria.getSelectedItem() == "Todas") {
            categoria = null;
        } else {
            categoria = (Categoria) jComboBoxCategoria.getSelectedItem();
        }
        if (jComboBoxSubCategoria.getSelectedItem() == "Todas") {
            subcategoria = null;
        } else {
            subcategoria = (Subcategoria) jComboBoxSubCategoria.getSelectedItem();
        }
        Date dataInicio = jDateInicio.getDate();
        Date dataFim = jDateFim.getDate();
        if (veiculo == null && categoria == null && subcategoria == null) {
            listLancamento = lancamentoController.consultarLancamento(dataInicio, dataFim);
        } else if (categoria == null && subcategoria == null) {
            listLancamento = lancamentoController.consultarLancamento(veiculo, dataInicio, dataFim);
        } else if (veiculo == null && categoria == null) {
            listLancamento = lancamentoController.consultarLancamento(subcategoria, dataInicio, dataFim);
        } else if (veiculo == null && subcategoria == null) {
            listLancamento = lancamentoController.consultarLancamento(categoria, dataInicio, dataFim);
        } else if (categoria == null) {
            listLancamento = lancamentoController.consultarLancamento(veiculo, subcategoria, dataInicio, dataFim);
        } else if (veiculo == null) {
            listLancamento = lancamentoController.consultarLancamento(categoria, subcategoria, dataInicio, dataFim);
        } else if (subcategoria == null) {
            listLancamento = lancamentoController.consultarLancamento(veiculo, categoria, dataInicio, dataFim);
        } else if (categoria != null && veiculo != null && subcategoria != null) {
            listLancamento = lancamentoController.consultarLancamento(veiculo, categoria, subcategoria, dataInicio, dataFim);
        }
        ResultSet resultSetAuxiliar = null;
        for (Lancamento lancamento : listLancamento) {
            model.addRow(new Object[]{
                lancamento.getIdLancamento(),
                lancamento.getVeiculo(),
                lancamento.getCategoria(),
                lancamento.getSubCategoria(),
                lancamento.getValor(),
                lancamento.getDataRegistro()
            });
        }
    }

    public void carregaProprietario() {
        try {
            ResultSet resultSet = lancamentoController.consultarLancamento("proprietario");
            Proprietario proprietario = new Proprietario();
            while (resultSet.next()) {
                proprietario.setCPF_CNPJ(resultSet.getString(1));
                proprietario.setNome(resultSet.getString(2));
            }
            jTextFieldCPF_CNPJ.setText(proprietario.getCPF_CNPJ());
            jTextFieldProprietario.setText(proprietario.getNome());
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonExportarPDF;
    private javax.swing.JButton jButtonGerarGrafico;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboBoxCategoria;
    private javax.swing.JComboBox jComboBoxSubCategoria;
    private javax.swing.JComboBox jComboBoxVeiculo;
    private com.toedter.calendar.JDateChooser jDateFim;
    private com.toedter.calendar.JDateChooser jDateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLancamento;
    private javax.swing.JTextField jTextFieldCPF_CNPJ;
    private javax.swing.JTextField jTextFieldProprietario;
    // End of variables declaration//GEN-END:variables
}
